import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //docsSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually

  docsSidebar: [
    "intro",
    {
      type: "category",
      label: "Développement",
      items: [
        {
          type: "category",
          label: "Stack",
          items: ["dev/stack/intro"],
        },
        {
          type: "category",
          label: "NestJS",
          items: ["dev/nestjs/nest-ddd-cqrs"],
        },
        {
          type: "category",
          label: "MongoDB",
          items: [
            "dev/mongodb/aggregate/intro",
            "dev/mongodb/aggregate/add-fields",
          ],
        },
      ],
    },
    "books/intro",
  ],

  projectsSidebar: ["projects/intro", "projects/reachmaker"],
}

export default sidebars
